### PR TITLE
fix line break on due date and add some margin for printer friendlyness

### PR DESCRIPTION
**Pull request by looppi**
Small fixes to get the invoice look like a proper invoice.

### CODE REVIEW

**Comment by mlaitinen** [comment]
Thanks for contributing! And sorry for the response delay.

Has there been problems with the current 9.0 invoice template? With printers? The non-existing margins were intentional, but of course we'll have to fix that if they somehow mess up the prints.

It seems that the changes you have made could cause some unwanted overlapping and unnecessary page breaks. Check out these PDF's that I printed using the current 9.0 ([Finnish Invoice OLD.pdf](https://github.com/avoinsystems/l10n_fi_invoice/files/85128/Finnish.Invoice.OLD.pdf)) and with your branch ([Finnish Invoice NEW.pdf](https://github.com/avoinsystems/l10n_fi_invoice/files/85129/Finnish.Invoice.NEW.pdf)).

**Comment by looppi** [comment]
There has been couple of problems with the template, I got complaints about the footer and the margins. Logos and such were out of the printing area and it made the invoice look bad.

I haven't yet had time to fix the footer properly has most of it is now out of the printing area and the footer also loses all formatting made in the "footer manager" of Odoo.

Ok, it seems I've broken something, I'll look into this soon and fix overlaps and page breaks!

**Comment by mlaitinen** [comment]
Do you have an example invoice with broken layout? A printed & scanned perhaps?

**Comment by looppi** [comment]
I should be able to continue the work on this during the weekend, I'll get back to you! With printed things it'll take till tuesday.

**Comment by looppi** [comment]
Actually, I wasn't able to get the invoice to fit on one page until today. Are those pdfs from V9 because mine looks different starting from fonts or are you using some other addons along the l10n_fi_invoice?

I tested the layout with somewhat sensitive production data, I'll come up with sample data prints as soon as I have time for it.

**Comment by mlaitinen** [comment]
Yeah, those PDF's are from v9 community (20151124 nightly) and there are no other modules that affect the layout or fonts. Although it's possible that I don't have the proper fonts installed in that environment. The primary font seems to be Helvetica Neue.

**Comment by looppi** [comment]
It can always be the case that actually my environment is missing the fonts but it has been looking like that in every environment I've tried so far.

The current version looks printed like this:

This includes using smaller font size everywhere. Otherwise it was next to impossible to get to fit on one page. What's actually to note is that the PDF version shows original Odoo footer in the very bottom of the page but it's left out when printing. I'll provide pdf shortly.

lasku

**Comment by looppi** [comment]
Here's screenshot of the PDF (I was unable to upload PDF files to this PR)

selection_291

**Comment by mlaitinen** [comment]
Could you please send the pdf to miku@avoin.systems so I can compare it better?

**Comment by looppi** [comment]
I found another oddity: When in developer mode and printing two page invoice, the page header gets printed only on the first page and everything seems OK, but when disabling the developer mode the header gets printed on the second page too and the payment info section slips under the second page header. Screenshot attached.

Developer mode off:
selection_313

Developer mode on:
selection_312

**Pull request closed without merging**
